Реализовать метод для окончания экзамена
se-brown-2023/automated-testing-applicants-service pull request #29
Opened 2023-11-03 15:16 UTC by axothy

#18

2023-11-08 08:48 UTC, vitekkor requested changes

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        ExamSession session = sessionRepository.findById(uuid).get();
Тут лучше не get делать, а `orElseThrow(ExamSessionNotFoundException::new)`

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        boolean isExpired = checkSessionExpiration(uuid);
Давай сюда сразу передавать ExamSession - у тебя везде, где используется метод checkSessionExpiration, уже доступен ExamSession экземпляр и лишний раз делать запрос в бд не нужно

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        session.setFinishTimestamp(now.plus(session.getExam().getMaxDuration()));
Finish не надо проставлять. Он должен проставляться по факту завершения экзамена - с фронта соответствующий запрос должен прийти

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +            case EXPIRED -> session.setStatus(Status.FINISHED);
Если EXPIRED, то EXPIRED и должно остаться. Тут лучше exception бросить

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +                Duration duration = checkExamExpiration(uuid);
Давай сюда тоже сразу передавать ExamSession - лишний раз делать запрос в бд не нужно

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +                Duration duration = Duration.between(start, finish);
Тут нужно сравнивать start и currentTime

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +                yield duration.isPositive() ? duration : Duration.ZERO;
Тут можно по идее просто yield duration делать

2023-11-08 08:48 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        if (session.getStatus() == Status.STARTED) {
Это условие лишнее - если экзамен начат, то мы спокойно можем перезагрузить страницу и получить задачи снова

2023-11-10 17:03 UTC, axothy commented on common/database/src/main/java/com/sebrown2023/model/db/Task.java
> +    @JoinColumn(name="exam_id", nullable = false)
Урал

2023-11-10 17:04 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        ExamSession session = sessionRepository.findById(uuid).get();
Ок, сделал orElseThrow

2023-11-10 17:04 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        boolean isExpired = checkSessionExpiration(uuid);
Окей, теперь нет лишнего обращения к БД в этом методе

2023-11-10 17:04 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        session.setFinishTimestamp(now.plus(session.getExam().getMaxDuration()));
Сначала не так понял, теперь точно понял

2023-11-10 17:04 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +            case EXPIRED -> session.setStatus(Status.FINISHED);
Хорошо, исправлено

2023-11-10 17:05 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +                Duration duration = checkExamExpiration(uuid);
Ок

2023-11-10 17:05 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +                Duration duration = Duration.between(start, finish);
Исправил

2023-11-10 17:05 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        if (session.getStatus() == Status.STARTED) {
Убрал условие

2023-11-12 17:18 UTC, vitekkor requested changes

2023-11-12 17:18 UTC, vitekkor commented on common/database/src/main/java/com/sebrown2023/model/db/Task.java
> +import jakarta.persistence.JoinColumn;
Лишний импорт

2023-11-12 17:18 UTC, vitekkor commented on common/database/src/main/java/com/sebrown2023/model/db/ExamSession.java
> +    private LocalDateTime starTimestamp;
Тут не твой косяк, но надо исправить коль уж заметили - не `starTimestamp`, а `startTimestamp` (буква t у start была пропущена. Ну и методы setStartTimestamp и  getStartTimestamp должны быть

2023-11-14 19:56 UTC, axothy commented on common/database/src/main/java/com/sebrown2023/model/db/ExamSession.java
> +    private LocalDateTime starTimestamp;
Пофиксил

2023-11-14 19:56 UTC, axothy commented on common/database/src/main/java/com/sebrown2023/model/db/Task.java
> +import jakarta.persistence.JoinColumn;
Ок, убрал

2023-11-15 10:01 UTC, vitekkor approved these changes

2023-11-27 09:31 UTC, merged