feat: Add basic CI
se-brown-2023/automated-testing-applicants-service pull request #31
Opened 2023-11-05 13:36 UTC by skelter001

2023-11-08 08:54 UTC, vitekkor requested changes

2023-11-08 08:54 UTC, vitekkor commented on .github/workflow/build..exam-conduct-service.yml
> +        run: ./gradlew test --tests "*"
gradle build по умолчанию запускает тесты, так что отдельный step на тесты не нужен

2023-11-08 08:54 UTC, vitekkor commented on .github/workflow/build..exam-conduct-service.yml
название файла с двумя точками - точно так и задумано?

2023-11-08 09:16 UTC, skelter001 commented on .github/workflow/build..exam-conduct-service.yml
Нет, пофикшу

2023-11-20 12:54 UTC, vitekkor approved these changes

2023-11-20 12:55 UTC, merged