Created automated-testing-applicants-servive client for keycloak realm
se-brown-2023/automated-testing-applicants-service pull request #32
Opened 2023-11-06 02:23 UTC by axothy

2023-12-13 10:41 UTC, axothy commented
@vitekkor Экспортировал realm вместе с ролями для нашего проекта. 

Из того что понадобится:
"issuer":"http://localhost:<port>/realms/swe-brown-2023-realm"
"token_endpoint":"http://localhost:<port>/realms/swe-brown-2023-realm/protocol/openid-connect/token"
clientId: automated-testing-applicants-service
+ clientSecret

2023-12-16 16:32 UTC, vitekkor requested changes

2023-12-16 16:32 UTC, vitekkor commented on docs/keycloak/swe-brown-2023-realm-export.json
> +          {
Надо вот эту политику переделать - из-за неё не даёт импортировать.

Надо заменить на это

```json
          {
            "id": "173b5614-5acd-404a-9ac8-6fd47b8fc37b",
            "name": "Default Policy",
            "description": "A policy that grants access only for users within this realm",
            "type": "role",
            "logic": "POSITIVE",
            "decisionStrategy": "AFFIRMATIVE",
            "config": {
              "roles": "[{\"id\":\"default-roles-swe-brown-2023-realm\",\"required\":false}]"
            }
          }
```

2023-12-21 07:53 UTC, vitekkor approved these changes

2023-12-21 07:54 UTC, merged