Реализовать контроллер и логику управления сессиями
se-brown-2023/automated-testing-applicants-service pull request #34
Opened 2023-11-10 21:07 UTC by axothy

#15 

Добавил в exam-manage-service логику и контроллер управления сессиями. Также сделал ControlAdvice для обработки исключений но не уверен что сделал это правильно.

2023-11-10 21:09 UTC, axothy commented
Походу я опять лохонулся так как запушил сюда изменения из exam-conduct-service

2023-11-12 17:58 UTC, vitekkor commented
@axothy направь просто PR не в master ветку, а в ту ветку, от которой ты отводился

2023-11-14 19:48 UTC, axothy commented
> @axothy направь просто PR не в master ветку, а в ту ветку, от которой ты отводился

Направил

2023-11-15 10:18 UTC, vitekkor requested changes

2023-11-15 10:18 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        sessionRepository.delete(session);
Вроде бы можно удалять по id. Посмотри, там должен быть похожий метод

2023-11-15 10:18 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        sessionRepository.delete(session);
По идее должен быть метод удаления по id. get не надо перед этим делать будет

2023-11-15 10:18 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/controller/RestResponseEntityExceptionHandler.java
> +public class RestResponseEntityExceptionHandler extends ResponseEntityExceptionHandler {
Лучше по-другому сделать:
```java
@ControllerAdvice
public class GlobalExceptionHandler {
    @ExceptionHandler(ExamSessionException.class)
    public ResponseEntity<ApiErrorDto> handleApiError(ExamSessionException exception) {
        return ResponseEntity
                .status(exception.getStatus())
                .body(new ApiErrorDto(exception.getStatus().getReasonPhrase(), exception.getMessage()));
    }
}
```
ApiErrorDto например вот такой:
```java
public record ApiErrorDto(String status, String message) {
}
```
А ExamSessionException сделать чуть другим:
```java
public class ExamSessionException extends Exception {

    private final HttpStatus status;

    public ExamSessionException(HttpStatus status, String message) {
        super(message);
        this.status = status;
    }
    public HttpStatus getStatus() {
        return status;
    }
}
```

Ну и exception другие переделать: они по идее разные статусы могут выдавать - 404, 400, 410 и тд. А у тебя здесь всегда 404

2023-12-19 14:48 UTC, axothy commented on exam-manage-service/src/main/java/com/sebrown2023/service/ExamSessionServiceImpl.java
> +        sessionRepository.delete(session);
Да, действительно есть

2023-12-19 15:03 UTC, axothy commented on exam-manage-service/src/main/java/com/sebrown2023/controller/RestResponseEntityExceptionHandler.java
> +public class RestResponseEntityExceptionHandler extends ResponseEntityExceptionHandler {
Переделал их

2023-12-19 15:20 UTC, axothy commented
Правки в код внесены

2023-12-19 15:35 UTC, vitekkor requested changes

2023-12-19 15:35 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/controller/ExamSessionController.java
> +    @GetMapping(value = "/get/{uuid}")
Лучше сделать просто "/{uuid}". Тут сам метод GET говорит нам о том, что мы получем сессию

2023-12-19 15:35 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/controller/ExamSessionController.java
> +    @DeleteMapping(value = "/delete/{uuid}")
Лучше сделать просто "/{uuid}". Тут сам метод DELETE говорит нам о том, что мы удаляем сессию

2023-12-19 15:35 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/controller/ExamSessionController.java
> +    public ResponseEntity<ExamSession> createSession() {
Тут явно не хватает каких-то параметров запроса. У нас сессия привязана к экзамену, а мы тут ничего не передаём.

2023-12-19 15:35 UTC, vitekkor commented on common/database/build.gradle.kts
> +    implementation("org.springframework:spring-web:6.1.1")
Во-первых, никакие версии для spring зависимостей по возможности мы не указываем - они резолвятся через плагин. Во-вторых, зачем в модуле database зависимость на spring-web? Если без неё не работает какой-то компонент, то её следует в другой компонент и добавить.

НО! Вместо org.springframework:spring-web надо использовать implementation("org.springframework.boot:spring-boot-starter-web")

2023-12-19 20:12 UTC, axothy commented on common/database/build.gradle.kts
> +    implementation("org.springframework:spring-web:6.1.1")
Ок

Убрал зависимость из модуля database (случайно вышло)

2023-12-19 20:14 UTC, axothy commented on common/database/build.gradle.kts
> +    implementation("org.springframework:spring-web:6.1.1")
В модуле database на самом деле есть пакет exceptions, там конструкторы исключений принимают HttpStatus которому нужна данная зависимость. Тогда перенесу пакет с исключениями ?

2023-12-19 21:09 UTC, vitekkor commented on common/database/build.gradle.kts
> +    implementation("org.springframework:spring-web:6.1.1")
Да, перенеси. Они явно не должны быть в db модуле

2023-12-19 21:11 UTC, vitekkor approved these changes

2023-12-19 21:16 UTC, axothy commented on common/database/build.gradle.kts
> +    implementation("org.springframework:spring-web:6.1.1")
Уже готово

2023-12-20 06:03 UTC, merged