- Создан основной каркас сервиса.
se-brown-2023/automated-testing-applicants-service pull request #41
Opened 2023-12-20 16:53 UTC by ALTV2

Сделал ПР чтобы хоть что-то можно было посмотреть, но пока думаю, что пока это не имеет смысла. Завтра после 15:00 буду все доделывать по возможности.
Нужно выяснить какие endPoint-ы этого сервиса нужны на фронте и договориться о формате DTO.
задачи по сервису: 
- Реализовать все endPoint-ы.
- Настроить маппинг в мапперах. 
- Добавить кастомные Exceptions и проверки на null (сделать заглушки).
- Реализовать ExceptionHandler
- Добавить транзакционность там, где она необходима
- Прикрутить openApi и заменить Dto классы на модели из спецификации
- Добавить логирование
- Ну и прибраться в коде + устранить warningi и т.д.

2023-12-22 22:42 UTC, ALTV2 commented
По сути сервис реализован, но скорее всего остались мелки е баги которые будем отлавливать при тестировании с фронтом

Открытые доработки:
* реализовать ExceptionHandler
* добавить логирование

2023-12-23 20:26 UTC, vitekkor requested changes

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/TestService.java
> +        if (test.isPresent()) {
Можно проще:
```java
var test = testRepository.findTestById(testId).orElseThrow(NoElementException::new);
return testMapper.testToTestComponent(test);
```

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/TaskService.java
> +        if (task.isPresent()) {
```java
var task = taskRepository.findTaskById(taskId).orElseThrow(NoElementException::new);
return buildTaskComponent(task);
```

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/SubmissionService.java
> +        if (submission.isPresent()) {
orElseThrow

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamSessionService.java
> +        if (examSession.isPresent()) {
orElseThrow

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamSessionService.java
> +        if (examSession.isPresent()) {
orElseThrow

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamService.java
> +        if (exam.isPresent()) {
orElseThrow

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/src/main/resources/api/openapi.yml
> +  /exam_session:
Нужен метод для создания сессии

2023-12-23 20:26 UTC, vitekkor commented on exam-manage-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-security")
Убери security пока что. Добавим позже

2023-12-23 20:26 UTC, vitekkor commented on common/database/src/main/java/com/sebrown2023/repository/ExamSessionRepository.java
> +public interface ExamSessionRepository extends JpaRepository<ExamSession, UUID> {
Коль уж ты перешёл на JpaRepository, то в exam-conduct-service/build.gradle.kts измени зависимость одну:

`implementation("org.springframework.boot:spring-boot-starter-data-jdbc")` на `implementation("org.springframework.boot:spring-boot-starter-data-jpa")`

без неё у тебя падает сборка

2024-01-11 20:12 UTC, ALTV2 commented on exam-manage-service/build.gradle.kts
> +    implementation("org.openapitools", "openapi-generator", "7.1.0")
+

2024-01-11 20:12 UTC, ALTV2 commented on exam-manage-service/build.gradle.kts
> -springBoot {
+

2024-01-11 20:12 UTC, ALTV2 commented on exam-manage-service/src/main/java/com/sebrown2023/config/MapperConfig.java
> +public class MapperConfig {
+

2024-01-11 20:12 UTC, ALTV2 commented on exam-manage-service/src/main/java/com/sebrown2023/config/SpringConfig.java
> +public class SpringConfig {
+

2024-01-11 20:12 UTC, ALTV2 commented on exam-manage-service/src/main/java/com/sebrown2023/exceptions/UniversalException.java
> +public class UniversalException extends RuntimeException {
+

2024-01-11 20:13 UTC, ALTV2 commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamSessionService.java
> +        if (examSession.isPresent()) {
+

2024-01-11 20:13 UTC, ALTV2 commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamService.java
> +        if (exam.isPresent()) {
+

2024-01-11 20:13 UTC, ALTV2 commented on exam-manage-service/src/main/resources/api/openapi.yml
> +  /exam_session:
Реализовал *

2024-01-11 20:13 UTC, ALTV2 commented on exam-manage-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-security")
+

2024-01-11 20:13 UTC, ALTV2 commented on common/database/src/main/java/com/sebrown2023/repository/ExamSessionRepository.java
> +public interface ExamSessionRepository extends JpaRepository<ExamSession, UUID> {
+

2024-01-11 20:15 UTC, ALTV2 commented on exam-manage-service/build.gradle.kts
> +    implementation("org.openapitools", "openapi-generator", "7.1.0")
Без нее вроде бы валятся импорты в моделях, которые генерит opneApi-generator.

2024-01-11 21:35 UTC, vitekkor commented on exam-manage-service/build.gradle.kts
> +    implementation("org.openapitools", "openapi-generator", "7.1.0")
Это зависимость на сам openapi-generator. У меня в проекте по энтерпрайзу без этой зависимости всё работает

Да и в этом проекте в соседнем модуле без неё тоже всё ок

2024-01-11 21:40 UTC, vitekkor commented on exam-manage-service/src/main/java/com/sebrown2023/services/ExamService.java
> +        if (exam.isPresent()) {
Здесь имелось в виду, что надо как в комментах выше - `orElseThrow(NoElementException::new).

[1](https://github.com/se-brown-2023/automated-testing-applicants-service/pull/41#discussion_r1435694151)
[2](https://github.com/se-brown-2023/automated-testing-applicants-service/pull/41#discussion_r1435693683)

Потом проще будет писать exceptionHandler

2024-01-12 11:18 UTC, vitekkor approved these changes

2024-01-12 11:18 UTC, merged