Аутентификация и авторизация Keycloak в conduct и manage сервисах
se-brown-2023/automated-testing-applicants-service pull request #55
Opened 2024-01-13 09:15 UTC by axothy

#52 

По сути, пока непонятно нужна ли защита в conduct-service, там по идее все эндпоинты должны быть открытые. (неавторизованные пользователи начинают сессию, заканчивают, присылают задачи - все это они делают как неавторизованные лица). 

В manage-service всем эндпоинтам повесил аннотацию `@RolesAllowed({"ROLE_ADMIN"})`, так как пока мне непонятно какое разделение по ролям идет, у нас их несколько - ADMIN, EXAMINATOR, MANAGER. Потом можно скорректировать.

Токен JWT берется из Keycloak напрямую, можно обратиться ко мне с помощью по нему.

2024-01-14 22:58 UTC, vitekkor requested changes
1. Ребейз на мастер и резолв конфликтов
2. Исправить замечания
3. Вот [тут](https://www.baeldung.com/spring-boot-keycloak#dependencies) инструкция по настройке, которой я сам пользовался. Как будто у тебя тут какие-то лишние бины настраиваются. Не везде понял, зачем нужен тот или иной бин(

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .requestMatchers("/api/test/**").permitAll() // permit the class of test
Надо убрать, у нас есть api/test пути

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .requestMatchers("/**").permitAll() // permit all the routers after swagger-ui.html
Тоже убрать

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .formLogin(Customizer.withDefaults())
Тут у тебя withDefaults, а в 72 строке disable. Надо бы определиться)

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +    public WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations) {
Webclient нам тут вроде не нужен, мы им не пользуемся

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +    public static ExchangeFilterFunction errorHandler() {
Ну и это тоже вместе с webclient удалить надо

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +        return new KeycloakJwtAuthenticationConverter();
Можно просто повесить аннотацию `@Component` на `KeycloakJwtAuthenticationConverter` и не создавать бин вот так

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/resources/application.yml
> +keycloak:
Не совсем понятно зачем вот эти проперти нужны. Вроде как обычных spring.security.oauth2 должно хватить

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
Это лишнее. Webclient мы не используем

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +class KeycloakJwtAuthenticationConverter extends JwtAuthenticationConverter {
Зачем это нужно?

2024-01-14 22:58 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +class KeycloakRealmRolesGrantedAuthoritiesConverter implements Converter<Jwt, Collection<GrantedAuthority>> {
Зачем это нужно?

2024-01-14 23:13 UTC, axothy commented
Ееебать мой хуй

2024-01-17 11:10 UTC, axothy commented
@vitekkor И в этом пул реквесте после ребейза на мастер возникла проблема: хочет вмержить в мастер файлы, которые уже существуют. До сих пор не понял в чем проблема)

2024-01-17 11:15 UTC, axothy commented
@vitekkor Помогло следующее решение: "Use the Edit button when viewing the PR in GitHub to change the base branch to something other than master. Then switch it back to master and it will now correctly show only the changes from the most recent commits"

2024-01-17 11:30 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .requestMatchers("/api/test/**").permitAll() // permit the class of test
Ok

2024-01-17 11:32 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .requestMatchers("/**").permitAll() // permit all the routers after swagger-ui.html
Если `.requestMatchers("/**").permitAll()` убрать, то тогда к методам контроллера без аннотации `@RolesAllowed` все равно нельзя будет обратиться, а так у нас просто будут защищены те эндпоинты, на которых есть `@RolesAllowed`

2024-01-17 11:34 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .formLogin(Customizer.withDefaults())
Ok, не заметил)

2024-01-17 11:36 UTC, vitekkor commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +                .requestMatchers("/**").permitAll() // permit all the routers after swagger-ui.html
Окей

2024-01-17 11:37 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +    public WebClient webClient(ReactiveClientRegistrationRepository clientRegistrations) {
Согласен, не нужен

2024-01-17 11:38 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +    public static ExchangeFilterFunction errorHandler() {
Ok

2024-01-17 11:40 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +        return new KeycloakJwtAuthenticationConverter();
Ok

2024-01-17 11:43 UTC, axothy commented on exam-conduct-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
Ok

2024-01-17 11:45 UTC, axothy commented on exam-conduct-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
Я попробовал удалить, после этого Ибн ReactiveClientRegistrationRepository перестал создаваться при запуске spring приложения

2024-01-17 11:46 UTC, vitekkor commented on exam-conduct-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
А нам разве нужен ReactiveClientRegistrationRepository? Там по идее обычный должен быть. У нас просто всё приложение на обычном spring-web

2024-01-17 11:49 UTC, axothy commented on exam-conduct-service/src/main/java/com/sebrown2023/security/SecurityConfig.java
> +class KeycloakJwtAuthenticationConverter extends JwtAuthenticationConverter {
Это парсер токена по сути

2024-01-17 11:49 UTC, vitekkor commented on exam-conduct-service/src/main/resources/application.yml
> +keycloak:
Так их можно прописать в другом месте
```yaml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id:
            client-secret:
        provider:
          keycloak:
            token-uri: 
```

2024-01-17 11:53 UTC, axothy commented on exam-conduct-service/src/main/resources/application.yml
> +keycloak:
А точно, сделал так как ты написал. А как заинжектить теперь эти проперти в SecurityConfig класс?

2024-01-17 11:55 UTC, axothy commented on exam-conduct-service/build.gradle.kts
> +    implementation("org.springframework.boot:spring-boot-starter-webflux")
Сменил на `InMemoryClientRegistrationRepository`

2024-01-17 12:21 UTC, axothy commented
@vitekkor Я исправил замечания

2024-01-17 12:54 UTC, vitekkor commented on exam-conduct-service/src/main/resources/application.yml
> +keycloak:
autowire OAuth2ClientProperties

2024-01-17 12:55 UTC, vitekkor approved these changes

2024-01-18 20:25 UTC, merged